### ISSUE TITLE
Docs site fails to send confirmation email

### ISSUE THREAD

**Issue by Ghosts** [InstantASP/plato#10]
![image](https://user-images.githubusercontent.com/2401816/66860097-7cb76680-ef5a-11e9-8785-e7c2adb629fd.png)

Wasn't able to fully register an account to post on the docs site.

Was curious - is there any easy way to deploy from a pre-build container/image through Docker and/or Digital Ocean? Planned to ask that in the discussion site as well.

**Comment by InstantASP** [comment]
@Ghosts Thank you so much. We'll take a look at this as a top priority I'll pop an update here ASAP  👍

**Comment by InstantASP** [comment]
@Ghost - Thank you again for reporting this. I just wanted to confirm we have identified the problem, this is due to our locale files not being included within the publish profile. I'm afraid this is currently effecting most of the emails on our web site - apologies. I'm just testing the updates and will pop a commit here with the fix in the coming hours. Our site will be updated tomorrow to resolve this. 

With regards to Docker I do want to make it as easy as possible for anyone to get going with Plato. I appreicate at the moment you need to basically be a developer to publish Plato. At the moment we don't have a great story around CI / CD. This will change soon and whilst I can't promise Docker or DO specifically once we have more automation in place we will be offering builds for the most popular environments. 

If you don't mind Ghost I'm going to pop your Docker and Digital Ocean ideas within our ideas area @ https://plato.instantasp.co.uk/ideas - it's a little slow at the moment (I suspect in part due to the email issues you've identified) but hopefully this will get going as we gain more users.

I'll pop another update here once the email issues are fully resolved. Thank you again Ghost 👍

**Comment by Ghosts** [comment]
@InstantASP Awesome! Thank you for the update. Absolutely love the look and features of Plato and excited to delve into it a bit deeper.

**Comment by InstantASP** [comment]
Thanks @Ghosts I sincerely appreicate your kind words. Apologies for the email issues. Just to confirm this issue was fixed last night with [this commit](https://github.com/InstantASP/plato/commit/3026094155e443fe5468a4166ada03e18de3b229#diff-b45c2ba57609f97bc39d4975ccdf001c). 

We [released 1.0.4](https://github.com/InstantASP/plato/releases/tag/1.0.4) this morning which also includes this fix. Our web site is now running 1.0.4 so email issues on our own web site should also be resolved. Apologies for this. 

Please don't hesitate to respond if you encounter any further issues. Any and all feedback is sincerely appreicate especially around any problems you encounter. 

Thank you for helping improve Plato @Ghosts Your support is greatly appreciated. 

Best wishes for now, Ryan
