### ISSUE TITLE
Can't SetUp EventHandler - Instance failure.

### ISSUE THREAD

**Issue by alweish** [InstantASP/Plato#17]
Hi, 

v1.0.9 couldn't complete the setup process and throw the following exception:

> SetUp within Plato.Users.Badges.Handlers.SetUpEventHandler - Instance failure.

**Comment by alweish** [comment]
It was a SQL server version issue, Installed 2019 and worked fine!

**Comment by InstantASP** [comment]
Hi There,

Thank you so much for checking out Plato. Sorry to hear of the issues. Plato does require SQL Server 2016 or above. This requirement is mainly due to the use of the newer DateTimeOffset data type introduced in SQL Server 2016. If you install in earlier versions of SQL Server these fields will be marked with the variant data type which can lead to unexpected problems. 

If you encounter any further issues or I can help with anything of course please don't hesitate to respond. I hope you find Plato helpful :)
